### ISSUE TITLE
BUG反馈:  装备更换问题

### ISSUE THREAD

**Issue by MkbaKa** [TabooLib/adyeshach#13]
服务器版本核心：Spigot-1.12.2
插件版本：1.3.14
问题描述：为npc更换主副手/装备的gui内无法拖动物品  且关闭时会报错
![1](https://user-images.githubusercontent.com/66232677/132831424-1fb2bd38-36a1-41f7-b05f-32c8a49a2902.png)

**Comment by Bkm016** [comment]
Fixed
