### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Moki0** [TabooLib/adyeshach#2]
服务器NPC皮肤过多，一个一个上传会很麻烦，希望/adyeshachapi uploadskin 指令能提供一个批量上传的功能， 并且支持steve 或 alex的设置

不知道是不是我使用不当的问题，/adyeshach lookhere 只能更改眼睛朝向，不能更改身体朝向
希望提供一个一直看着玩家的功能

**Comment by 157946a** [comment]
本来就有一直看向
