### ISSUE TITLE
Feature: Add command to make private, public or temporary

### ISSUE THREAD

**Issue by Zarkness2** [TabooLib/Adyeshach#30]
Add command to make it private, public or temporary or an option in the config, if you make it private you can set that you need a permission to see it.

**Comment by Bkm016** [comment]
I can't understand, do you need commands to modify NPC data?

**Comment by Galaxy-VN** [comment]
> I can't understand, do you need commands to modify NPC data?

npc private like only that player can see other can't

**Comment by Zarkness2** [comment]
> I can't understand, do you need commands to modify NPC data?



> > I can't understand, do you need commands to modify NPC data?
> 
> npc private like only that player can see other can't
exactly what @Galaxy-VN  said the only thing is that in order to see it you would need a permit. @Bkm016

**Comment by Zarkness** [comment]
one thing, does anyone know of a region plugin that allows me to do this? https://imgur.com/a/5rktZNg

**Comment by Zarkness2** [comment]
sorry for taking so long to answer, but the classes had me busy, but if what I meant was what Galaxy said, that putting a condition to the npc or simply a permission either in the npc config or with a command, I would prefer from the config if I can say it, it would be appreciated, because I would like to put that the vips see certain npcs, that users can not see.
@Bkm016

**Comment by Zarkness2** [comment]
@Bkm016

**Comment by 157946a** [comment]
You can do this by adding a visual condition to the public, that is, npc trait id view-condition

**Comment by Zarkness2** [comment]
> You can do this by adding a visual condition to the public, that is, npc trait id view-condition

I don't know if this will change the npc from public to private. @157946a

**Comment by 157946a** [comment]
> > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> 
> I don't know if this will change the npc from public to private. @157946a

No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see

**Comment by Zarkness2** [comment]
> > > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> > 
> > 
> > I don't know if this will change the npc from public to private. @157946a
> 
> No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see

ok, thank you very much a few questions, is it possible to put that 1 npc for each user has a different skin? and you can put that for that you need or not a permission?

**Comment by 157946a** [comment]
> > > > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> > > 
> > > 
> > > I don't know if this will change the npc from public to private. @157946a
> > 
> > 
> > No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see
> 
> ok, thank you very much a few questions, is it possible to put that 1 npc for each user has a different skin? and you can put that for that you need or not a permission?

Someone mentioned your question. I asked the developer, but he didn't say whether it was possible or not. Some users said that they could use variables, but I don't know how to use them. The only way is to test or look at the code by yourself.

**Comment by Zarkness2** [comment]
and finally with the events would be possible to make a system of skins like this? what would be that when you put /skin or any other command will appear an npc with 2 arrows one for each side and would be changing the skin and you would go previewing the skins to choose the one you like, clearly would have to be done with support to skinrestorer or any other plugin /skin, or for that already would have to make a plugin to part?

![image](https://user-images.githubusercontent.com/48263644/184084001-5c69109a-ff2f-49a5-9758-79fab1fcaa1a.png)

**Comment by Zarkness2** [comment]
> > > > > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> > > > 
> > > > 
> > > > I don't know if this will change the npc from public to private. @157946a
> > > 
> > > 
> > > No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see
> > 
> > 
> > ok, thank you very much a few questions, is it possible to put that 1 npc for each user has a different skin? and you can put that for that you need or not a permission?
> 
> Someone mentioned your question. I asked the developer, but he didn't say whether it was possible or not. Some users said that they could use variables, but I don't know how to use them. The only way is to test or look at the code by yourself.

ok, but it would be better if you can do it either from config or by commands rather than by events, because for something that should come by default in the plugin I would have to do it myself or anyone else.

**Comment by 157946a** [comment]
> > > > > > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> > > > > 
> > > > > 
> > > > > I don't know if this will change the npc from public to private. @157946a
> > > > 
> > > > 
> > > > No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see
> > > 
> > > 
> > > ok, thank you very much a few questions, is it possible to put that 1 npc for each user has a different skin? and you can put that for that you need or not a permission?
> > 
> > 
> > Someone mentioned your question. I asked the developer, but he didn't say whether it was possible or not. Some users said that they could use variables, but I don't know how to use them. The only way is to test or look at the code by yourself.
> 
> ok, but it would be better if you can do it either from config or by commands rather than by events, because for something that should come by default in the plugin I would have to do it myself or anyone else.

The author has mentioned the function of uploading pictures. You download the namemc skin, put it in the specified path, and use it directly after uploading, you don’t need to look at it one by one.

**Comment by Zarkness2** [comment]
> > > > > > > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> > > > > > 
> > > > > > 
> > > > > > I don't know if this will change the npc from public to private. @157946a
> > > > > 
> > > > > 
> > > > > No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see
> > > > 
> > > > 
> > > > ok, thank you very much a few questions, is it possible to put that 1 npc for each user has a different skin? and you can put that for that you need or not a permission?
> > > 
> > > 
> > > Someone mentioned your question. I asked the developer, but he didn't say whether it was possible or not. Some users said that they could use variables, but I don't know how to use them. The only way is to test or look at the code by yourself.
> > 
> > 
> > ok, but it would be better if you can do it either from config or by commands rather than by events, because for something that should come by default in the plugin I would have to do it myself or anyone else.
> 
> The author has mentioned the function of uploading pictures. You download the namemc skin, put it in the specified path, and use it directly after uploading, you don’t need to look at it one by one.

my idea is to put that 1 user the npc appears for example with the skin of doraemon and to another with the skin of goku, and to part that can choose if they need a permission for that or not.

**Comment by 157946a** [comment]
> > > > > > > > You can do this by adding a visual condition to the public, that is, npc trait id view-condition
> > > > > > > 
> > > > > > > 
> > > > > > > I don't know if this will change the npc from public to private. @157946a
> > > > > > 
> > > > > > 
> > > > > > No, private NPCs belong to the trigger person in the sense, not for anyone to see, you can only use the public to set visual conditions, so that players who pass the conditions can see
> > > > > 
> > > > > 
> > > > > ok, thank you very much a few questions, is it possible to put that 1 npc for each user has a different skin? and you can put that for that you need or not a permission?
> > > > 
> > > > 
> > > > Someone mentioned your question. I asked the developer, but he didn't say whether it was possible or not. Some users said that they could use variables, but I don't know how to use them. The only way is to test or look at the code by yourself.
> > > 
> > > 
> > > ok, but it would be better if you can do it either from config or by commands rather than by events, because for something that should come by default in the plugin I would have to do it myself or anyone else.
> > 
> > 
> > The author has mentioned the function of uploading pictures. You download the namemc skin, put it in the specified path, and use it directly after uploading, you don’t need to look at it one by one.
> 
> my idea is to put that 1 user the npc appears for example with the skin of doraemon and to another with the skin of goku, and to part that can choose if they need a permission for that or not.

You are a bit similar to the menu using variables to get the player's head skin

**Comment by Zarkness2** [comment]
ok, but couldn't it be done in some easier way than making some event or variable?

**Comment by 157946a** [comment]
> ok, but couldn't it be done in some easier way than making some event or variable?

At present, only using variables is the easiest, followed by developing plugins

**Comment by Zarkness2** [comment]
Well, couldn't this option be added directly to the plugin to be able to do it without having to use variables?

**Comment by Zarkness2** [comment]
> You can do this by adding a visual condition to the public, that is, npc trait id view-condition
now that I remember to put a permission on that it would be something like /npc trait id view-condition permission permission.test?

**Comment by 157946a** [comment]
No, you don't need to write parameters later, because he will open a book and write there

**Comment by 157946a** [comment]
But he can only make it possible for players to see NPCs. As for what you said, each player sees different skins, I don't quite understand it yet.

**Comment by Zarkness2** [comment]
then how would you put it so that they need a permit in the book?

**Comment by 157946a** [comment]
You need to write the kether grammar in the open book. For example, if you write perm test in the book, it means that he needs the permission test to see it.

**Comment by Zarkness2** [comment]
ok, then if I want to put that to see it they need for example to have level 20 in this https://www.spigotmc.org/resources/cyberlevels-%E2%9C%A8-custom-rewards-%E2%9A%A1-mysql-support-%E2%9A%A1%E3%80%8C1-7-1-19%E3%80%8D.98826/ plus level 100 of island in the superiorskyblock2, plus 1 permission that I would have to put?

**Comment by 157946a** [comment]
Then you need to compare this variable, same as java, js, example 'check papi %% == yes'

**Comment by 157946a** [comment]
The content of %% belongs to the variable you need to compare

**Comment by Zarkness2** [comment]
ok, thanks, one thing to make an npc spawnee in each island that is created and that the user can move it like the npc of the islands of the skyblock of hypixel, for that if I need a plugin to part right?

**Comment by 157946a** [comment]
This may require skyblock to be compatible with adyeshach, I don't know the specific content, you can ask the author

**Comment by Zarkness2** [comment]
> This may require skyblock to be compatible with adyeshach, I don't know the specific content, you can ask the author

I would try but he doesn't usually answer

**Comment by 157946a** [comment]
Oh no, I seem to have read it wrong, I haven't understood much about the content of Hypixel, so you can only understand it yourself

**Comment by Zarkness2** [comment]
> Oh no, I seem to have read it wrong, I haven't understood much about the content of Hypixel, so you can only understand it yourself

I explain in the skyblock of hypixel each user in their island have an npc which you give and opens a menu and within the menu has an option to move the npc, which does is give you an egg with which you move the npc.

![image](https://user-images.githubusercontent.com/48263644/184094478-b2d627bd-e0b8-4f80-9cd8-f0b9259221c2.png)
![image](https://user-images.githubusercontent.com/48263644/184094528-5919d535-f428-4d36-93d9-fcae31765035.png)
![image](https://user-images.githubusercontent.com/48263644/184094554-fd05b2d9-d164-4c2f-b869-ace570b9a92b.png)

**Comment by 157946a** [comment]
This seems to be compatible and provided by the Sky Island plug-in. I haven't seen this function on citizens. Maybe I missed it, or he used another plug-in to do it.

**Comment by Zarkness2** [comment]
hypixel uses its own plugins so it is normal that you have not seen it in the citizens, there are already some addons like this https://github.com/mdaffa48/IslandNPC but I feel it lacks things, it is outdated and the dev is not very active that's why I was asking.

**Comment by 157946a** [comment]
This you can only ask the developer or develop a plugin with similar functions based on adyeshach, I can't do anything about it

**Comment by Zarkness2** [comment]
okey
