### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by mfcc168** [TabooLib/Adyeshach#47]
1，npc太多会很难编辑，要在资料夹里一个一个找，而且还是乱码名。建议新增资料夹分类或文件名自定义
2，是否可以增加npc坐下的动作？

**Comment by mfcc168** [comment]
主要问题还是因爲npc edit能设置的东西太少，而且设置名字在木牌打十分不方便，不能copy&paste

**Comment by Bkm016** [comment]
1. 本身ady是不允许编辑文件的，编辑文件可能会产生极其危险的数据包，因为并不会实装「资料夹分类或文件名自定义」
2. trait sit 可以使 npc 坐下
