### ISSUE TITLE
功能增强 

### ISSUE THREAD

**Issue by CivicXFB** [TabooLib/Adyeshach#51]
我发现我在使用Triat tilte时 NPCtilte是纯文本我使用变量没有任何翻译希望坏黑能修复

**Comment by Bkm016** [comment]
<img width="854" alt="Xnip2022-10-17_12-41-01" src="https://user-images.githubusercontent.com/27818531/196090833-c95eac7e-de4c-4ac1-92b8-487dec1ba022.png">

<img width="390" alt="image" src="https://user-images.githubusercontent.com/27818531/196090864-0b589aab-2964-4ffc-a8bf-8e1e8a00380f.png">
