### ISSUE TITLE
[BUG] 一些小问题汇总

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/adyeshach#54]
测试环境：
spigot - 1.16.5
Adyeshach-1.5.13-op15

**1、实体姿势为 SLEEPING 时，名称标签偏移位置与姿势不匹配**

![image](https://user-images.githubusercontent.com/64759847/197247425-b4cf2ab5-4148-495a-92c8-5a4cbd8117d8.png)
![image](https://user-images.githubusercontent.com/64759847/197247459-abc808a1-9bb3-4195-a2aa-1862b47cec9f.png)

**2、实体姿势 SPIN_ATTACK 疑似未生效，名称标签偏移好像也不匹配**

![image](https://user-images.githubusercontent.com/64759847/197248277-8c9d8954-5a37-4830-8b03-b14f91c84c56.png)

**3、实体姿势 DYING 疑似未生效**

![image](https://user-images.githubusercontent.com/64759847/197249477-dcf38560-23d8-4bca-8657-75b214371be6.png)

**4、猫无法定义颜色，被定义的是项圈色，和狼一样（还是原本就是这么设计的？但是记得猫好像有不同颜色的变种）**

![image](https://user-images.githubusercontent.com/64759847/197249792-f8d0a7b0-1116-4f37-b539-a0fd513f189d.png)

**5、羊无法定义颜色**

![image](https://user-images.githubusercontent.com/64759847/197254314-de52595e-0215-4c44-a130-7f640a350ed5.png)

**6、船的左转动和右转动动画不生效**

![image](https://user-images.githubusercontent.com/64759847/197255767-7fbe485f-62a5-42b8-9734-eae9b2d4c2a8.png)

**7、蜜蜂生成几秒后，飞行动画不再渲染**

![image](https://user-images.githubusercontent.com/64759847/197255855-5ca4d80b-6e43-4b40-979b-2f6d04114df3.png)

**Comment by Bkm016** [comment]
**Adyeshach 所提供的单位均为发包实现的虚拟实体，虽提供所有元数据的编辑方式，但不代表均可有效。**

> 1、实体姿势为 SLEEPING 时，名称标签偏移位置与姿势不匹配

SLEEPING 状态只有实体脚下方块为床时才可以躺在正常的地方。

> 4、猫无法定义颜色，被定义的是项圈色，和狼一样

猫的颜色是指项圈，变种是颜色左侧的类型

 > 5、羊无法定义颜色

功能缺陷，这里已经告诉你了：
<img width="95" alt="image" src="https://user-images.githubusercontent.com/27818531/197454447-1b9775fa-e1d4-4c20-8674-bbddae22dfbc.png">

**Comment by Bkm016** [comment]
🤫 换句话说就是，这包我发了，但是客户端没反应我也不知道为什么。

**Comment by luoxiawuchen** [comment]
> **Adyeshach 所提供的单位均为发包实现的虚拟实体，虽提供所有元数据的编辑方式，但不代表均可有效。**
> 
> > 1、实体姿势为 SLEEPING 时，名称标签偏移位置与姿势不匹配
> 
> SLEEPING 状态只有实体脚下方块为床时才可以躺在正常的地方。
> 
> > 4、猫无法定义颜色，被定义的是项圈色，和狼一样
> 
> 猫的颜色是指项圈，变种是颜色左侧的类型
> 
> > 5、羊无法定义颜色
> 
> 功能缺陷，这里已经告诉你了： <img alt="image" width="95" src="https://user-images.githubusercontent.com/27818531/197454447-1b9775fa-e1d4-4c20-8674-bbddae22dfbc.png">

原来如此，感谢坏黑大佬的耐心解答

**Comment by luoxiawuchen** [comment]
> 🤫 换句话说就是，这包我发了，但是客户端没反应我也不知道为什么。

mojang的锅（bushi），不过确实都是无伤大雅的小问题，刚好遇到就反馈一下了

**Comment by Bkm016** [comment]
https://github.com/TabooLib/adyeshach/blob/master/src/main/kotlin/ink/ptms/adyeshach/common/entity/EntityMetas.kt
https://wiki.vg/Entity_metadata#Sheep

羊作为 Minecraft 的元老级生物，它的数据包结构是所有实体中最牛逼的。
直到 Adyeshach v2 都没有办法支持对其进行颜色修改。

**Comment by luoxiawuchen** [comment]
> https://github.com/TabooLib/adyeshach/blob/master/src/main/kotlin/ink/ptms/adyeshach/common/entity/EntityMetas.kt https://wiki.vg/Entity_metadata#Sheep
> 
> 羊作为 Minecraft 的元老级生物，它的数据包结构是所有实体中最牛逼的。 直到 Adyeshach v2 都没有办法支持对其进行颜色修改。

我看不懂，但大受震撼，看样子是对其的逆向程度还不够？（wiki是干货，收藏了）
另外，如果坏黑大佬后面还有意向弄Adyeshach-wiki的话，可以看看我能否参与wiki编写的协助工作，因为打算长期使用，应该多多少少能熟悉一些内容，不过我很菜就是了（

**Comment by Bkm016** [comment]
我一直想写wiki，但奈何太忙了。恢复wiki编写工作可能要等待v2版本发布之后。

**Comment by luoxiawuchen** [comment]
> 我一直想写wiki，但奈何太忙了。恢复wiki编写工作可能要等待v2版本发布之后。

原来是这么个情况，很能理解，毕竟大家都得为生活奔波。
