### ISSUE TITLE
[Closed] feature: add support to itemsadder

### ISSUE THREAD

**Issue by Zarkness2** [TabooLib/adyeshach#63]
add support to itemsadder to be able to put custom skins on npcs

**Comment by Bkm016** [comment]
don't understand itemadder, please tell me the documentation of the specific function 🤔

**Comment by Zarkness2** [comment]
the idea was to add support to the itemsadder which is this plugin to put custom textures to the npcs with texture pack which is what the itemsadder is in charge of creating a texturepack.

https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/

@Bkm016

**Comment by Bkm016** [comment]
Sorry, itemsadder does not support binding models to virtual entities

```java
    /**
     * Spawns a CustomEntity and returns the created CustomEntity instance, or null if Namespace and ID are invalid.
     *
     * @param namespacedId Namespace and ID in the format {@code namespace:id} to get the CustomEntity from.
     * @param bukkitEntity the Bukkit entity you want to convert.
     * @return Possibly-null CustomEntity instance.
     */
    @Nullable
    public static CustomEntity convert(String namespacedId,
                                       LivingEntity bukkitEntity)
```

It requires a BukkitEntity as a carrier, which adyeshach does not have:

> @param bukkitEntity the Bukkit entity you want to convert.

😰

**Comment by Bkm016** [comment]
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomEntity.java

**Comment by Zarkness2** [comment]
> Sorry, itemsadder does not support binding models to virtual entities
> 
> ```java
>     /**
>      * Spawns a CustomEntity and returns the created CustomEntity instance, or null if Namespace and ID are invalid.
>      *
>      * @param namespacedId Namespace and ID in the format {@code namespace:id} to get the CustomEntity from.
>      * @param bukkitEntity the Bukkit entity you want to convert.
>      * @return Possibly-null CustomEntity instance.
>      */
>     @Nullable
>     public static CustomEntity convert(String namespacedId,
>                                        LivingEntity bukkitEntity)
> ```
> 
> It requires a BukkitEntity as a carrier, which adyeshach does not have:
> 
> > @param bukkitEntity the Bukkit entity you want to convert.
> 
> 😰

ok, so nothing, I will have to put npcs with custom skin or if I can do it with citizens I prefer to do it with adyeshach since it is more optimized and it allows me to only look at the npc with the condition that I put, thank you very much anyway.

**Comment by LoneDev6** [comment]
You can spawn custom entities without having to provide a BukkitEntity.
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomEntity.java#L99
Use `noBase=true`.

```java
    public static CustomEntity spawn(String namespacedId,
                                     Location location,
                                     boolean frustumCulling,
                                     boolean noBase,
                                     boolean noHitbox)
```

**Comment by Bkm016** [comment]
@Zarkness what it `namespacedId`? can you give me an example, I don't have itemsadder 🥹

> Namespace and ID in the format {@code namespace:id} to get the CustomEntity from.

**Comment by Zarkness2** [comment]
> @Zarkness what it `namespacedId`? can you give me an example, I don't have itemsadder 🥹
> 
> > Namespace and ID in the format {@code namespace:id} to get the CustomEntity from.
@Bkm016 

from what I'm looking at the namespace:id is namespace = name of the category, id = name or id of the item or npc within that category.

I haven't been using itemsadder long enough to explain perfectly what is what.

I don't know what @LoneDev6 will say about that since he is the plugin dev and knows better if I am right or not.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/plugin-usage/adding-content/configs-and-resourcepack#what-is-a-namespace

**Comment by Zarkness2** [comment]
@Bkm016 hi?

**Comment by Zarkness2** [comment]
Hi, @Bkm016 could you pass me the documentation of the plugin api?

**Comment by LoneDev6** [comment]
> Hi, @Bkm016 could you pass me the documentation of the plugin api?

Please read the wiki.
Everything is explained.

**Comment by Zarkness2** [comment]
> > Hi, @Bkm016 could you pass me the documentation of the plugin api?
> 
> Please read the wiki. Everything is explained.

I can't find the link

**Comment by Zarkness2** [comment]
@Bkm016 hello?

**Comment by Zarkness** [comment]
Hi, I'm trying to compile the plugin and I'm getting an error, could someone help me?

**Comment by Zarkness2** [comment]
how do i set the npc to execute a command when i click on it?

**Comment by Bkm016** [comment]
@Zarkness Sorry, I can't respond to questions in time due to work reasons 🥹

**Comment by Zarkness2** [comment]
> @Zarkness Sorry, I can't respond to questions in time due to work reasons 🥹

nothing happens, it is normal to take a long time to answer, either because you forget, because of work or whatever, as long as you end up answering when you can nothing happens. @Bkm016

**Comment by Bkm016** [comment]
> Hi, @Bkm016 could you pass me the documentation of the plugin api?

new doc: https://a.ptms.ink

**Comment by Zarkness2** [comment]
ok, thank you very much, can you pass me the link to the wiki where it tells me how to add a command to the npc for when a user clicks on it?

I was looking and I saw that you have to buy the plugin and I was wondering from where I could buy it and if it would be possible to buy the latest but only one payment or permanent and not have to pay annually.

**Comment by Bkm016** [comment]
Adyeshach 的文档是公开的，插件也是免费的，暂无海外支付方式。如果你使用的是 Adyeshach 2.0 以上的版本，你可以直接在 `/npc edit` 中编辑交互命令。

> https://a.ptms.ink/docs/start/command/editor/public-traits

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/27818531/230709578-09bbb3ec-1939-4061-92a2-9d42be132f14.png">

---

The documentation for Adyeshach is public, and the plugins are also free. Currently, there are no overseas payment methods available. If you are using Adyeshach version 2.0 or above, you can directly edit the interaction commands in `/npc edit`.

**Comment by Zarkness2** [comment]
ok, thank you very much, that's what happens for looking quickly at the documentation, using the translator to understand it and not reading it well hahahaha.

then I will wait to see if in the future you can buy from abroad.

**Comment by Zarkness2** [comment]
One thing would it be possible to help with the translation of the wiki even with the translator?

**Comment by Bkm016** [comment]
> One thing would it be possible to help with the translation of the wiki even with the translator?

🫶

**Comment by Galaxy-VN** [comment]
> > One thing would it be possible to help with the translation of the wiki even with the translator?
> 
> 
> 
> 🫶

I can help you in translate wiki

**Comment by Zarkness2** [comment]
> > One thing would it be possible to help with the translation of the wiki even with the translator?
> 
> 🫶
The only thing to help with the translation is how do I do it since I don't have access to the repository or anything on the wiki.

The only thing I don't have much time, I usually wake up between 8 and 10 am spanish time and then in the evenings I'm around 21 or 22 spanish time, plus then my minecraft server project.

**Comment by Zarkness2** [comment]
> > > One thing would it be possible to help with the translation of the wiki even with the translator?
> > 
> > 
> > 🫶
> 
> I can help you in translate wiki

If you want to help me better, I don't have much free time, so it would take me a long time to finish the translation.

**Comment by Galaxy-VN** [comment]
> > > > One thing would it be possible to help with the translation of the wiki even with the translator?
> 
> > > 
> 
> > > 
> 
> > > 🫶
> 
> > 
> 
> > I can help you in translate wiki
> 
> 
> 
> If you want to help me better, I don't have much free time, so it would take me a long time to finish the translation.
Its fine anyway

**Comment by Galaxy-VN** [comment]
Its fine for me anyway 
> > > > One thing would it be possible to help with the translation of the wiki even with the translator?
> 
> > > 
> 
> > > 
> 
> > > 🫶
> 
> > 
> 
> > I can help you in translate wiki
> 
> 
> 
> If you want to help me better, I don't have much free time, so it would take me a long time to finish the translation.
