### ISSUE TITLE
Could not resolve all files for configuration ':project:module-bukkit:taboo'.

### ISSUE THREAD

**Issue by Martinligabue** [TabooLib/adyeshach#68]
I followed Readme: macOS/Linux 平台 ./gradlew clean build
I got https://scans.gradle.com/s/zkftbhlx7buya

**Comment by ItsEricRao** [comment]
same :(

**Comment by ItsEricRao** [comment]
> I followed Readme: macOS/Linux 平台 ./gradlew clean build I got https://scans.gradle.com/s/zkftbhlx7buya

Fixed it by editing gradle.properties. 
change taboolib_version to 6.0.11-13.

**Comment by Martinligabue** [comment]
fixed with latest version: https://github.com/TabooLib/adyeshach/commit/9c761041bfefe56ed812c3764e755c8ea0a8d4e8
