### ISSUE TITLE
[Closed] 'MaterialData' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by shuiqing2046** [TabooLib/adyeshach#69]
`
w: D:\adyeshach\project\common\src\main\kotlin\ink\ptms\adyeshach\core\MinecraftEntityMetadataHandler.kt: (8, 28): 'MaterialData' is deprecated. Deprecated in Java
`
`w: D:\adyeshach\project\common\src\main\kotlin\ink\ptms\adyeshach\core\MinecraftEntityMetadataHandler.kt: (76, 53): 'MaterialData' is deprecated. Deprecated in Java
`
`w: D:\adyeshach\project\common\src\main\kotlin\ink\ptms\adyeshach\core\MinecraftEntityMetadataHandler.kt: (81, 56): 'MaterialData' is deprecated. Deprecated in Java`

**Comment by Bkm016** [comment]
不影响
