### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness2** [TabooLib/adyeshach#7]
hello a question is it possible to add support for citizens addons?

**Comment by Bkm016** [comment]
你好

目前来说不会
因为 Citizens 是有服务端实体的，而 Adyeshach 无服务端实体，逻辑上无法互通。

---

Hi
The principle is different, not possible currently
Citizens has server-side entities, but Adyeshach not

**Comment by Bkm016** [comment]
通过 Adyeshach API 可以完成绝大多数需求
如有需要可以自行编写扩展，Adyeshach 不会对非付费用户提供任何技术支持。

---

Adyeshach API is complete enough.
You can write your own addons if necessary, and Adyeshach will not provide any substantial support to free users.

Just like TrMenu.

**Comment by Zarkness2** [comment]
Ok, so if I want support for the adyeshach I will need to buy it? and about the previous issue it was not a question but rather a suggestion to add to the adyeshach.

**Comment by Zarkness2** [comment]
by the way how much is it worth, where could I buy it, what kind of support would I get when I buy it and if what I order/suggest could be added to the plugin?

**Comment by Zarkness2** [comment]
@Bkm016 Hi, I think you forgot to answer my last question.

**Comment by Zarkness2** [comment]
another thing could you translate what it says in the last 3 lines of this image, since I don't know Chinese, I only know Spanish and English? it's from your plugin Chemdah, is to change the betonquests, for yours.
![image](https://user-images.githubusercontent.com/48263644/115276701-a64ee080-a143-11eb-94e6-fc5fa05c2e0e.png)

**Comment by Bkm016** [comment]
Hi, Contact my discord (Bkm016#4472)

**Comment by Zarkness2** [comment]
I am ! Zarkness#0291 I just sent you a friend request
