### ISSUE TITLE
[特性] Ady2的头衔和私有容器的问题

### ISSUE THREAD

**Issue by TH2403y** [TabooLib/adyeshach#76]
私有容器里的NPC设定的头衔会显示给非指定玩家

我使用Ady2的Kether语句来创建NPC [ 使用私有化容器 -> 创建NPC -> 给予头衔 ] 使用的脚本如下:
def main = {
  use private temporary
  create *quest_yuelin *allay at location zc 560 79 329
  select *quest_yuelin
  controller add LookAtPlayerAlways
  meta set noGravity to true
  trait title to [ "Allay &7[Guider]" ]
}
然后用指令指定一个玩家运行脚本 被指定的玩家显示了NPC以及名字，头衔 另一个非指定玩家视角凭空出现一个头衔

能否令私有容器的NPC的头衔不显示在所有玩家的视角中?

**Comment by Bkm016** [comment]
头衔目前暂不支持私有化
