### ISSUE TITLE
[功能建议] 支持Model Engine 4.x（模型引擎4.0）

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/adyeshach#78]
希望重新支持Model Engine，为adyeshach外观渲染层面带来更多可能（不仅限于原版模型）

Model Engine 4链接：https://mythiccraft.io/index.php?resources/model-engine%E2%80%94ultimate-entity-model-manager-1-19-4-1-20-4.1213/

**Comment by Bkm016** [comment]
我不会啊

**Comment by Bkm016** [comment]
已支持
