### ISSUE TITLE
[报错]Adyeshach-2.0.1在Paper1.12.2版本启动报错

### ISSUE THREAD

**Issue by MySoulcutting** [TabooLib/adyeshach#81]
![9ea45833e0f7de3d5b6a0a34f7960283](https://github.com/TabooLib/adyeshach/assets/72398605/564372a1-32a7-44ed-9ea0-7c85119b204c)
![b36d39ab9d5c2f006383fd8400b198be](https://github.com/TabooLib/adyeshach/assets/72398605/1867b4de-7f26-4776-af32-3c7f8c671026)
无法启动

**Comment by TheFloodDragon** [comment]
刷新服务端缓存：删除 /libraries/io/izzel/taboolib/common-env 及 /cache/taboolib

若还是不行就删除Gradle缓存，使用`taboolib-gradle-plugin`的`refreshDependencies`任务，并重新构建

**Comment by MySoulcutting** [comment]
> 刷新服务端缓存：删除 /libraries/io/izzel/taboolib/common-env 及 /cache/taboolib
> 
> 若还是不行就删除Gradle缓存，使用`taboolib-gradle-plugin`的`refreshDependencies`任务，并重新构建

这是不是taboolib6.1的问题?

**Comment by TheFloodDragon** [comment]
> > 刷新服务端缓存：删除 /libraries/io/izzel/taboolib/common-env 及 /cache/taboolib
> > 若还是不行就删除Gradle缓存，使用`taboolib-gradle-plugin`的`refreshDependencies`任务，并重新构建
> 
> 这是不是taboolib6.1的问题?

是。6.1之后的特性。

**Comment by Bkm016** [comment]
tb 6.1.0 截止 2024/2/13 依旧是 Pre release

**Comment by Bkm016** [comment]
用旧版本即可
