### ISSUE TITLE
[报错] 我从2.0.0升级到2.0.14后看见之前的npc会出现大量错误刷屏

### ISSUE THREAD

**Issue by Mikoto-qiuhua** [TabooLib/adyeshach#88]
我一直以为是某个依赖没下载到 多次尝试后 删掉了旧的npc文件之后就正常了
![image](https://github.com/TabooLib/adyeshach/assets/102891248/d0cf421e-f92d-4231-8540-5e7ea6ca2089)
[错误.log](https://github.com/user-attachments/files/15534991/default.log)

**Comment by Bkm016** [comment]
好的

**Comment by Bkm016** [comment]
已被修复
