### ISSUE TITLE
kether脚本 select的by有什么用

### ISSUE THREAD

**Issue by Jeffrey131313** [TabooLib/adyeshach#91]
如题，select {action} [by (id|uuid)]
我一开始以为是by 玩家ID 选择属于玩家的私有化NPC，但是测试了下好像不是？这样用会报错

**Comment by Bkm016** [comment]
`select Jeffrey131313` 等价于 `select Jeffrey131313 by id`，指通过 ID 选择。
`select 27a66a0b-847f-441f-8b81-1c158447467d by uuid` 指通过 UUID 选择。

**Comment by Jeffrey131313** [comment]
> `select Jeffrey131313` 等价于 `select Jeffrey131313 by id`，指通过 ID 选择。 `select 27a66a0b-847f-441f-8b81-1c158447467d by uuid` 指通过 UUID 选择。

明白了，谢谢
